# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=30, verbose_name='商品类别')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodsname', models.CharField(max_length=30, verbose_name='商品名字')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('introduction', models.CharField(max_length=30, verbose_name='商品介绍')),
                ('image', models.ImageField(upload_to='goods/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
