# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit',
            field=models.CharField(default='斤', max_length=10, verbose_name='单位'),
        ),
    ]
