# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_num', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'db_table': 'check',
            },
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('goods_num_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价格')),
                ('name', models.CharField(max_length=10, verbose_name='收件人')),
                ('phone', models.CharField(max_length=11, verbose_name='收件人电话')),
                ('adress', models.CharField(max_length=50, verbose_name='实际收货地址')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'db_table': 'checkout',
            },
        ),
    ]
