# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-08 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='r_id',
            field=models.IntegerField(default=0, max_length=6, verbose_name='关联record_trade表id'),
        ),
    ]
