# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-08 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20191008_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='r_id',
            field=models.IntegerField(default=0, verbose_name='关联record_trade表id'),
        ),
    ]
